version: 2
updates:
  # Go modules (backend)
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    target-branch: "develop"
    reviewers:
      - "@matthewyuh246"
    assignees:
      - "@matthewyuh246"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️ [dev]"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "go"

  # npm (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    target-branch: "develop"
    reviewers:
      - "@matthewyuh246"
    assignees:
      - "@matthewyuh246"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️ [dev]"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    # セキュリティアップデートは優先
    versioning-strategy: increase-if-necessary

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    target-branch: "develop"
    reviewers:
      - "@matthewyuh246"
    assignees:
      - "@matthewyuh246"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    target-branch: "develop"
    reviewers:
      - "@matthewyuh246"
    assignees:
      - "@matthewyuh246"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
